---
couchbase_nodes:
  - hostname: ec2-54-217-191-55.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - data
  - hostname: ec2-34-247-48-133.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - data
  - hostname: ec2-54-217-158-84.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - data
  - hostname:   ec2-34-242-188-11.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - data
  - hostname:   ec2-54-217-168-153.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - data
  - hostname: ec2-54-77-37-146.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - index
  - hostname:   ec2-54-78-239-190.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - index
  - hostname: ec2-34-244-53-21.eu-west-1.compute.amazonaws.com
    group: eu-west-1a
    services:
      - query
  - hostname: ec2-54-216-65-118.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - data
  - hostname: ec2-54-75-56-192.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - data
  - hostname: ec2-54-171-230-113.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - data
  - hostname:   ec2-18-202-250-188.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - data
  - hostname: ec2-34-240-8-78.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - data
  - hostname: ec2-34-243-250-127.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - index
  - hostname: ec2-34-241-68-195.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - index
  - hostname: ec2-3-250-125-56.eu-west-1.compute.amazonaws.com
    group: eu-west-1b
    services:
      - query
  - hostname: ec2-18-203-249-122.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - data
  - hostname:   ec2-34-244-41-165.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - data
  - hostname: ec2-54-78-165-185.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - data
  - hostname:   ec2-3-249-191-163.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - data
  - hostname: ec2-3-252-130-208.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - data
  - hostname: ec2-54-155-51-101.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - index
  - hostname: ec2-34-247-89-58.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - index
  - hostname: ec2-54-246-44-246.eu-west-1.compute.amazonaws.com
    group: eu-west-1c
    services:
      - query

couchbase_cluster:
  name: doctolib-poc
  protocol: http
  port: 8091
  notifications: true
  index_storage: default
  default_services:
    - data
    - index
    - query

couchbase_security:
  admin_user: Administrator
  admin_password: password
  disable_http_ui: false
  disable_www_authenticate: false
  cluster_encryption_level: control
  tls_min_version: tlsv1
  tls_honor_cipher_order: true

couchbase_memory_quotas:
  data: 217600
  index: 217600

couchbase_rebalance_settings:
  rebalance_retry: false
  wait_for: 300
  max_attempts: 1
  moves_per_node: 4

couchbase_index_settings:
  max_rollback_points: 2
  stable_snapshot_interval: 5000
  memory_snapshot_interval: 200
  threads: 0
  log_level: info

couchbase_query_settings:
  pipeline_batch: 16
  pipeline_cap: 512
  scan_cap: 512
  timeout: 0
  prepared_limit: 16384
  completed_limit: 4000
  completed_threshold: 1000
  log_level: info
  max_parallelism: 1

couchbase_autofailover:
  enabled: false
  failover_timeout: 30
  max_failovers: 1
  failover_of_server_groups: false
  failover_on_data_disk_issues: true
  failover_data_disk_period: 30
  can_abort_rebalance: true
